### ISSUE TITLE
t3086t เข้าไป m71f01 ปี 57 Error ครับ

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#47]
t3086t เข้าไป m71f01 
ของปี 57  แล้ว Error ครับ

เป็นเพราะอะไรครับ

**Comment by dbuaklee** [comment]
## สาเหตุ
หน้าจอนี้เคยมีการตรวจสอบค่า การ sign off การจัดสรรงบประมาณ (เป็น code ที่ไม่ได้ใช้แล้วนะครับ) ปรากฏว่า ตอนการตรวจสอบมีการบันทึกข้อมูล sign off ไปด้วย แต่คงจะมี bug ทำให้เคยบันทึกข้อมูลเบิ้ล เลยปรากฎ error ดังกล่าว
 result returns more than one elements

## การแก้ไข & ป้องกัน
ผมเอา code ส่วนที่ตรวจสอบการ sign off ออกไปแล้วครับ

Commit ID:  4594ba67df98f16ceca40e557015c96ea8fd3923
