### ISSUE TITLE
Error!!!!!  t1774t จัดสรร M73f03 Error

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#48]
582011201 แผนปฏิบัติการประชาสัมพันธ์เพื่อเกษตรกร (ส.)(ย.5)(ผง.3)(เงินสงเคราะห์รับ) 
เข้าไปจัดสรร แล้ว Error ตามรูป 
![27-01-2558 16-02-17](https://cloud.githubusercontent.com/assets/7665473/5915861/482bc5a2-a63d-11e4-8adf-5937178b954d.jpg)

ตรวจสอบแล้วดักบัก ให้ด้วยนะครับ
สาเหตุมาจากอะไร ขอวิธีแก้ไขให้ด้วยนะครับ

**Comment by dbuaklee** [comment]
## สาเหตุ 
มีการจัดสรรเป้าหมายให้กับ สกย.จ.พง. ในกิจกรรมนี้ ซ้ำ ครับ 
1. Log in ด้วย t2608t (กองประชาสัมพันธ์และเผยแพร่) 
2. ไปที่ menu m73f02 
3. เลือกแผนปฏิบัติการ 5820112 และกิจกรรมรอง 582011201 
4. เลือกกิจกรรมย่อยรายการวิทยุ ที่มีเป้าหมาย 800 ครั้ง

ปรากฎว่า รายการจัดสรรให้หน่วยงาน มันเบิ้ล (จะเห็นว่าจัดสรรรวม 1,600 ครั้ง) สันนิษฐานว่า เวลาเจ้าหน้าที่กดปุ่มบันทึก คงจะกดเบิ้ลไปสองครั้ง โดยพร้อมๆ กัน เลยทำให้ข้อมูลมัน save เบิ้ล พอเวลา จังหวัดมาจัดสรรต่อในหน้า m73f03 เลยทำให้มันเจอเป้าหมายสองบรรทัด เลยเกิด error ตอนจะ save ว่า result return one more element ตาม error ด้านบนครับ

## การแก้ไข
กุ๊กเข้าไปลบรายการในหน้า m73f02 ที่ซ้ำได้เลยครับ login ด้วย กองประชาสัมพันธ์และเผยแพร่

## การป้องกัน
ผมแก้ code ให้ disable ปุ่มบันทึกเวลากดบันทึก จนกระทั่งบันทึกเสร็จเรียบร้อยจึงจะ enable กลับมาครับ คิดว่าไม่น่าจะเกิดกรณีเบิ้ลได้อีกครับ

commit id : 87f39de2f6aff844504fb77f87438117528c5b0d
