### ISSUE TITLE
Error!!!!! t2689t  M73f01 ลบ กิจกรรมย่อยสวนค้างตรวจ/สวนระงับดำเนินการ

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#49]
t2689t แผน 5820201 กิจกรรมรอง 58202101 
จะลบกิจจกรมย่อย   สวนค้างตรวจ และ สวนระงับดำเนินการ 
Error 
![03-02-2558 16-26-52](https://cloud.githubusercontent.com/assets/7665473/6017509/0341ef96-abc1-11e4-804a-8af4ad6dd31d.jpg)

กุ๊กเดาว่าน่าจะเป็นที่่ มีการจัดสรรใน M73f02 แล้วหรือเปล่า 
ถ้าไม่ใช่ แล้ว 
ลบกิจกรรมย่อย ที่สร้างไว้แล้ว แล้ว มีการจัดสรร ไปให้จังหวัด  แล้วจังหวัด มีการจัดสรรแล้วให้ อำเภอ แล้ว อำเภอ ทำแผนและผลแล้ว มันจะต้องสามารถลบ   
แต่การลบนั้น จะต้องมีการแจ้งเตือน ทุกครั้ง ด้วยนะครับ 

ขอบคุณครับ

**Comment by dbuaklee** [comment]
**สาเหตุ:** code ที่ทำการลบกิจกรรม มีการลบข้อมูลผิด order  โดยกรณีนี้ เกิดจาก มีการรายงานผลกิจกรรมแล้ว (ตาราง PLN_ACTIVITYTARGETREPORT) แต่ไปลบตารางที่ระบุความรับผิดชอบจากการจัดสรรให้จังหวัด ไปก่อน (ตาราง PLN_ACTIVITYPERFORMANCE) ทำให้เกิด integrity constraint 

**การแก้ไขปัญหา:**  เรียงลำดับการลบข้อมูลใหม่แล้ว สามารถเข้าไปลบกิจกรรมได้ โดยระบบจะไปลบข้อมูลการจัดสรรและการรายงานผลการดำเนินงานให้ โดยอัตโนมัติ **(เมื่อลบแล้วไม่สามารถ undo ได้)**

commit: a4477ae40c8160eb1e96ce107c6f26c8d2de38d8
