### ISSUE TITLE
Error!!!!! t0660t งบลงทุน

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#50]
1. ปี 2556 เลือกทำแผนงบลง แล้วError อาจมาจากไม่พบ รหัสหน่วยงาน 

2. การทำแผนและผล ของ งบลงทุน เมื่อทำการกดบันทึก แล้วมันไม่ refresh หน้าจอ

ตรวจสอบให้ด้วยครับ
ขอบคุณครับ

**Comment by dbuaklee** [comment]
ทดสอบแล้วไม่พบปัญหานะครับ ถ้ายังงัยมีปัญหาใหม่ เปิด issue มาใหม่นะครับ


เดช
