### ISSUE TITLE
Error!!!!! รหัส t1413t จะลบ กิจกรรมย่อย ไม่ได้

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#51]
1.	รหัส t1413t จะลบ กิจกรรมย่อย    ในแผนปฏิบัติการบริหารทั่วไป  กิจกรรมรอง กิจกรรมบริหารทั่วไป   กิจกรรมย่อย จัดทำเอกสารเผยแพร่ทางวิชาการ (test)   และ  แผนปฏิบัติการสนาม กิจกรรมรอง กิจกรรมสำรวจสวน กิจกรรมย่อย test และ กิจกรรมสำรวจสวน แล้ว Error ดังรูป   

![11](https://cloud.githubusercontent.com/assets/7665473/6632617/c1916af4-c96b-11e4-9012-520a47245b1f.png)

เป็นเพราะอะไรครับ  ดักError  บอกวิธีแก้ไขอย่างไรครับ

2.ตรวจสอบการลบกิจกรรมย่อยทีครับ เพราะเหมือน  User จะลบกิจกรรม test และ กิจกรรมสำรวจสวน    แต่ไปลบ อีกกิจกรรม 

ขอบคุณครับ

**Comment by dbuaklee** [comment]
1. ลบข้อมูลกิจกรรมด้านบนให้หมดแล้วครับ และแก้ไข Code ให้เช็ครายละเอียดของตารางย่อยที่มี reference ไปที่ตาราง activity ให้ถูกต้องครับ code เดิม เช็ตตก ไปครับ พอลบแล้วเลยขึ้น integrity constraint ครับ
2. การลบกิจกรรมเมื่อกดแล้ว จะ Delete ที่ database เลยครับ ตอนนี้ไม่ได้เก็บ Log ไว้ว่าใคร login เข้ามาลบอะไรเมื่อไรครับ ตรวจสอบไม่ได้ครับ 

commit#  89e1514f06deb185dbe33cea8d1c70afcad4d1c0
