### ISSUE TITLE
Error!!!!!  รหัส t1774t m73f03: บันทึกและถ่ายค่าเป้าหมายและงบประมาณ (ระดับจังหวัด)

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#52]
รหัส t1774t m73f03: บันทึกและถ่ายค่าเป้าหมายและงบประมาณ (ระดับจังหวัด) จัดสรร แผนปฏิบัติการประชาสัมพันธ์เพื่อเกษตรกร (ส.)(ย.5)(ผง.3)(เงินสงเคราะห์รับ) / งบทำการ (ส.-cess)  จัดสรร กิจกรรมย่อย รายการวิทยุ และ รหัส 1128 แผนปฏิบัติเดียวกัน กิจกรรมย่อยเดียวกันด้วยครับ  แล้ว Error ดังรูป

![22](https://cloud.githubusercontent.com/assets/7665473/6632668/c30b90ca-c96c-11e4-86ca-3a1c388820ec.png)

 เป็นเพราะอะไรครับ   ดัก Error วิธีแก้ไขอย่างไรครับ
ขอบคุณครับ

**Comment by dbuaklee** [comment]
กรณีนี้เกิดจาก มีการเบิ้ลค่าการจัดสรรเป้าหมายครับ ตามรูปด้านล่าง login เข้าไปด้วย user กปผ. (t2608t) เลือก m73f02 แผนปฏิบัติการ 5820112 กิจกรรมรอง 582011201 ครับ เลือก รายการวิทยุ ก็จะเห็นว่ามันเบิ้ลอยู่ครับ

![image](https://cloud.githubusercontent.com/assets/1902603/6652283/84b7f8e6-ca9c-11e4-97db-7bd7265a5ef6.png)

เข้าใจว่า user กดบันทึกเบิ้ลครับ ผมแก้ไข code ให้ disable ตอนบันทึกแล้วนะครับ ไม่น่าจะเกิดขึ้นอีก ให้ user เข้าไปลบได้เลยครับ ผมลบข้อมูลที่ซ้ำให้หมดแล้วครับ
