### ISSUE TITLE
จะแก้ไขผลเงิน ติดต่อกัน มันจะ Error ดังรูปครับ 

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#53]
จะแก้ไขผลเงิน ติดต่อกัน มันจะ Error ดังรูปครับ 
![33](https://cloud.githubusercontent.com/assets/7665473/6632674/f3a0771e-c96c-11e4-9ea1-69a560535c3c.png)

**Comment by dbuaklee** [comment]
เกิด error จาก javascript code ที่ instantiate object ใหม่ โดยใช้ id เดิม ซึ่ง ส่งค่ากลับมาผิดจาก java ครับ แก้ไข code แล้วครับ

commit# 4f253cf101c327d4769cdf5ad1d99d5cbb4d1cde
