### ISSUE TITLE
การบันทึก แผน-ผล (งบลงทุน) 

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#54]
m74f02: บันทึกแผนงบลงทุน
m81f02: บันทึกผลการดำเนินงานงบลงทุน
เมื่อทำการบันทึกข้อมูลเสร็จสิ้น เรียบร้อย แล้วไม่กลับหน้าจอหลัก 
แก้ไขให้ทีครับ
ขอบคุณครับ

**Comment by dbuaklee** [comment]
แก้ไขแล้วครับ เมื่อกดบันทึกข้อมูล และแจ้งแสดงว่าบันทึกแล้วเสร็จ จะกลับไปที่หน้าจอหลักครับ

commit# cb2f5b2bd005c74114378351f2d5631d1acf6630
