### ISSUE TITLE
t0660t งบลงทุน ปี 56 

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#55]
เข้ารหัส t0660t  เข้าเมนู m74f02: บันทึกแผนงบลงทุน เลือกแผนปฏิบัติการบริหารงานทั่วไป   
Error
![16-03-2558 14-05-22](https://cloud.githubusercontent.com/assets/7665473/6661756/46861d0c-cbe4-11e4-8e34-6874cab24320.jpg)
บันทึกผลก็เช่นเดียวกันนะครับ
แก้ไขให้ทีครับ ขอบคุณครับ

**Comment by dbuaklee** [comment]
เกิดจาก หน่วยงานรหัส 101350300 (ส่วนพัฒนาระบบสื่อสารข้อมูล) ถูกเปลี่ยนไปเป็นกอง (id: 101350700) เดิมใน view HRX_ORGANIZATION จะ มี where inactive='N' เพื่อเลือกให้มีข้อมูลเฉพาะหน่วยงานที่ยังคง active อยู่เท่านั้น หน่วยงานที่ถูก set ให้ inactive ='Y' แต่เคยได้รับการจัดสรรงบประมาณแล้ว จึงหาข้อมูลใน view นี้ไม่ได้ จึงเกิด error 

__การแก้ไข__
1. แก้ไข view HRX_ORGANIZATION  ให้มีค่า inactive มาด้วย
2. แก้ไขการ query เรียกหน่วยงานมาจัดสรรงบประมาณ ให้ เพิ่ม where inactive='N' ไปด้วย เพื่อจะได้ดึงเฉพาะหน่วยงานที่ยังคง active อยู่เท่านั้น

commit# 345160f5c324fffd528bc2b1a679d35dcbe1ffa0
