### ISSUE TITLE
ยอดเงินใน m71f01: บันทึกการจัดสรรงบประมาณ ผิดพลาด 

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#56]
ตามรูปเลยครับ 
![16-03-2558 14-09-15](https://cloud.githubusercontent.com/assets/7665473/6661810/24309740-cbe5-11e4-8b1d-fdda0d0ca119.jpg)

ตรวจสอบให้ทีครับ

**Comment by dbuaklee** [comment]
ตรวจสอบแล้ว มี record ของการจัดสรรงบประมาณอยู่ครับ อาจจะเกิดจาก
1. เคยมีการผูกผลผลิต/โครงการ ใหม่ หลังจากเคยมีกาiจัดสรรงบประมาณไปแล้ว

ตอนนี้ลบรายการจัดสรรนี้ไปแล้วครับ
