### ISSUE TITLE
 t2452t ในระบบ รายงาน(r) 

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#57]
ในระบบ   รายงาน(r)  เห็นเมนู  m81r11: รายงานการสรุปผลการเบิกจ่ายงบลงทุน (เฉพาะรายการที่รับผิดชอบ)
2 อัน ครับ 

แก้ไขให้ด้วยครับ
ขอบคุณครับ

**Comment by dbuaklee** [comment]
มีเมนู เบิ้ลครับ พิมพ์เกิน.. ลบออกไปแล้วครับ

commit# a8171c7baa2b33bddd08b881b86ea80df667891e
