### ISSUE TITLE
รหัส t0957t ห.สบท นคร 1 ออกรายงานงบลงทุน ปี งปม. 2557 ไม่เจอ ข้อมูล 

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#58]
รหัส t0957t ห.สบท นคร 1   เลือกปี งปม. 2557  ออกรายงานงบลงทุน  ทั้ง 
m81r11: รายงานการสรุปการเบิกจ่ายงบลงทุน (เฉพาะรายการที่รับผิดชอบ)
m81r10: รายงานการสรุปรายการครุภัณฑ์ (เฉพาะรายการที่รับผิดชอบ)
ไม่เจอข้อมูลเลยครับ

แก้ไขให้ด้วย
ขอบคุณครับ

**Comment by dbuaklee** [comment]
Query เลือกมาไม่ครบครับ แก้ไขแล้วครับ

commit# 5f7813459ab44f625c05117214e5bc2350e55a86
commit# 5a628fed647359ca6c4d963978a66ee417828f62
