### ISSUE TITLE
M81r02 เลือกหน่วยงานมีปัญหา ครับ

### ISSUE THREAD

**Issue by cokcok** [orraf/eBudgeting#59]
รหัส t3212t  เข้าไปที่ m81r02 เลือก สกย.จ. ขอนแก่น  
แล้ว สกย.อ. มันขึ้นมาเกิน ดังรูป 
![17-03-2558 13-34-19](https://cloud.githubusercontent.com/assets/7665473/6682291/03e33302-cca9-11e4-90bc-1d5558d93b9f.jpg)

ของอีกหลายที่ก็เหมือนกันนะครับ 
ตรวจสอบให้ด้วยครับ
ขอบคุณครับ

**Comment by dbuaklee** [comment]
query การเลือกหน่วยงานมาแสดงผล ไม่ได้ filter หน่วยงานที่ไม่ active แล้ว (inActive == 'Y') ออกนะครับ 

แก้ไขแล้วครับ
commit# 801a6f364492ea8e70ec425133ceb67d9ecd4e38
